// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Holding struct {
	ID               int64
	UserID           pgtype.UUID
	StockCode        string
	Quantity         int64
	AcquisitionPrice pgtype.Numeric
	CreatedAt        pgtype.Timestamptz
}

type Stock struct {
	Code string
	Name string
}

type StockPrice struct {
	StockCode   string
	TradingDate pgtype.Date
	ClosePrice  pgtype.Numeric
	FetchedAt   pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}
