// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock_prices.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertClosingPrice = `-- name: UpsertClosingPrice :exec
INSERT INTO stock_prices (stock_code, trading_date, close_price)
VALUES ($1, $2, $3)
ON CONFLICT (stock_code, trading_date)
DO UPDATE SET close_price = EXCLUDED.close_price, fetched_at = now()
`

type UpsertClosingPriceParams struct {
	StockCode   string
	TradingDate pgtype.Date
	ClosePrice  pgtype.Numeric
}

// 銘柄 stock_code の取引日 trading_date の終値を保存する。同じ銘柄・同じ取引日の行がすでにあれば、
// 終値を取得した値で上書きし、取得日時も今に更新する（再取得した値を正とし、成功として扱う。FR-15）。
// 取得日時は、追加するときは列の DEFAULT now() に任せる。
func (q *Queries) UpsertClosingPrice(ctx context.Context, arg UpsertClosingPriceParams) error {
	_, err := q.db.Exec(ctx, upsertClosingPrice, arg.StockCode, arg.TradingDate, arg.ClosePrice)
	return err
}
